        Console.WriteLine("Character Generator");
        Console.WriteLine("Введите расу вашего персонажа:");
        string raceCharacter =  Console.ReadLine();
        Console.WriteLine("Введите класс вашего персонажа:");
        string classCharacter = Console.ReadLine();
        Console.WriteLine("Введите возраст персонажа:");
        int  ageCharacter = int.Parse(Console.ReadLine());
        Console.WriteLine("Введите силу вашего персонажа:");
        int  strength = int.Parse(Console.ReadLine());
        Console.WriteLine("Введите ловкость персонажа:");
        int  dexterity = int.Parse(Console.ReadLine());
        Console.WriteLine("Введите интеллект персонажа:");
        int  intelligence = int.Parse(Console.ReadLine());
        int globalSum = strength + dexterity + intelligence;
        int health = 100 + strength * 10;
        int attack = strength * 2 + dexterity;
        int mana = 50 + intelligence * 5;
        int boost = (intelligence + attack + mana) * 10;
        int endurance = health + intelligence + dexterity;
        int recovery = (health + mana) / 100;

        Console.WriteLine("Ваш персонаж:");
        Console.WriteLine($"Общая сумма характеристик: {globalSum}");
        Console.WriteLine($"Здоровье: {health}");
        Console.WriteLine($"Атака: {attack}");
        Console.WriteLine($"Мана: {mana}");
        Console.WriteLine($"Раса: { raceCharacter}");
        Console.WriteLine($"Класс: {classCharacter}");
        Console.WriteLine($"Возраст: {ageCharacter}");
        Console.WriteLine($"Сила: { strength}");
        Console.WriteLine($"Ловкость: {dexterity}");
        Console.WriteLine($"Интеллект: {intelligence}");
        Console.WriteLine($"Мутация: {boost}");
        Console.WriteLine($"Выносливость: {endurance}");
        Console.WriteLine($"Восстановление: {recovery} %");
